### PR TITLE
enable flash unprotected on init

### PR DESCRIPTION
**Pull request by lanxb**
We need change the flash status to unprotected before write and erase operate,no matter what chip.write_mode

### CODE REVIEW

**Comment by armink** [comment]
这段修改有在哪些 Flash 上做过测试呢？

**Comment by lanxb** [comment]
test MX25L3206E

**Comment by lanxb** [comment]
There is no guarantee that the chips are completely new, and block protection may be enabled during use, so it should be removed at initialization  
image

**Comment by yangjie11** [comment]
测试未通过，硬件pandora
测试日志：

image

**Comment by lanxb** [comment]
我没使用QSPI,正常单线模式  
STM32F105RC + MX25L3206E

**Comment by lanxb** [comment]
MX25L3206E硬件上WP和HOLD都直接上拉高电平了  
W25Q128 有两个状态寄存器，不太一样  
image

**Comment by armink** [comment]
或者读取到 MX25L3206E 系列的 ID 后特殊处理一下？

**Comment by lanxb** [comment]
手上没那么多 flash ,我这边加ID处理吧

**Pull request merged**
